name: CI

on:
  push:
  pull_request:
    branches:
      - master

jobs:
  build-docker:
    name: Build Docker

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: false
          cache-from: type=registry,ref=emmanuelgautier/docker-python-ci-example:latest
          cache-to: type=inline
          tags: emmanuelgautier/docker-python-ci-example:latest
